name: Node.js Setup
description: Setup Node.js for CI/CD
runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: .tool-versions