name: Website

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: ci
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: ./.github/actions/setup-node
      - name: Install dependencies
        run: yarn install --immutable
      - name: Build
        run: yarn build
        working-directory: ./website
