name: Examples

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: build
    steps:
      - name: Setup
        uses: ./.github/actions/setup
      - name: Build
        run: yarn prebuild && yarn build
        working-directory: ./examples/react
