name: CI

on: [pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    name: ci
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install dependencies
        run: yarn install --immutable
      - name: Check Type
        run: yarn typecheck
      - name: Check Lint
        run: yarn lint
      - name: Run Test
        run: yarn test
      - name: Run Build
        run: yarn build
