name: CI

on: [pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    name: ci
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Check Lint
        run: yarn lint
      - name: Run Test
        run: yarn test
      - name: Build Package
        run: yarn build
      - name: Slack Notify Sanity
        if: success()
        id: react-calendar-sanity-notifiction-success
        uses: voxmedia/github-action-slack-notify-build@v1.1.2
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
        with:
          message_id: ${{ steps.slack.outputs.message_id }}
          channel: react-calendar-github
          status: SUCCESS
          color: good
      - name: Slack Notify Sanity
        if: failure()
        id: react-calendar-sanity-notifiction-fail
        uses: voxmedia/github-action-slack-notify-build@v1.1.2
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
        with:
          message_id: ${{ steps.slack.outputs.message_id }}
          channel: react-calendar-github
          status: FAILED
          color: danger
