name: CI

on: [pull_request]

jobs:
  integration:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['18', '20', '22']
    name: CI (Node.js ${{ matrix.node }})
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: yarn install --immutable
      - name: Check Type
        run: yarn typecheck
      - name: Check Lint
        run: yarn lint
      - name: Run Test
        run: yarn test
      - name: Run Build
        run: yarn build
