name: Pull Request Labeler

on:
  pull_request_target:
    types:
      - opened
      - synchronize

jobs:
  label:
    name: Create Label
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
