name: Release

on:
  push:
    branches:
      - main
      - alpha
      - beta

jobs:
  release:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          # do not change this version, because of semantic-release, npm whoami bug
          # see with https://github.com/semantic-release/npm/issues/470
          node-version: 16.15.0
      - name: Install dependencies
        run: yarn install --immutable
      - name: Check Type
        run: yarn typecheck
      - name: Check Lint
        run: yarn lint
      - name: Run Test
        run: yarn test
      - name: Build Package
        run: yarn build
      - name: Release to npm registry
        run: yarn semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}