name: Release

on:
  push:
    branches:
      - main
      - alpha
      - beta

jobs:
  release:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: yarn install --immutable
      - name: Build Package
        run: yarn build
      - name: Release to npm registry
        uses: cometkim/yarn-changeset-action@v1
        with:
          autoPublish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
