name: sanity

on:
  schedule:
    - cron: 0 0 * * *

jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Cypress run
        uses: cypress-io/github-action@v2
      - name: Slack Notify Sanity
        if: success()
        id: react-calendar-sanity-notifiction
        uses: voxmedia/github-action-slack-notify-build@v1.1.2
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          message_id: ${{ steps.slack.outputs.message_id }}
          channel: react-calendar-github
          status: SUCCESS
          color: good
      - name: Slack Notify Sanity
        if: failure()
        id: react-calendar-sanity-notifiction
        uses: voxmedia/github-action-slack-notify-build@v1.1.2
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          message_id: ${{ steps.slack.outputs.message_id }}
          channel: react-calendar-github
          status: FAILED
          color: danger