name: sanity

on:
  schedule:
    - cron: 0 15 * * *

jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Install Playwright
        run: npx playwright install-deps
      - name: Run CI
        working-directory: packages/calendar
        run: yarn run test:playwright
      - name: Slack Notify Sanity
        if: success()
        id: react-calendar-sanity-notification-success
        uses: voxmedia/github-action-slack-notify-build@v1.5.0
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          message_id: ${{ steps.slack.outputs.message_id }}
          channel: react-calendar-github
          status: SUCCESS
          color: good
      - name: Slack Notify Sanity
        if: failure()
        id: react-calendar-sanity-notification-fail
        uses: voxmedia/github-action-slack-notify-build@v1.5.0
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          message_id: ${{ steps.slack.outputs.message_id }}
          channel: react-calendar-github
          status: FAILED
          color: danger
